<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="mensabot">

  <!-- ===================== MATERIALIEN ===================== -->
  <material name="grey"><color rgba="0.5 0.5 0.5 1"/></material>
  <material name="black"><color rgba="0 0 0 1"/></material>
  <material name="blue"><color rgba="0 0 1 1"/></material>
  <material name="green"><color rgba="0 1 0 1"/></material>
  <material name="red"><color rgba="1 0 0 1"/></material>
  <material name="white"><color rgba="1 1 1 1"/></material>

  <!-- ===================== GLOBALE PARAMETER ===================== -->
  <xacro:property name="rod_weight_per_meter" value="1.549"/>

  <!-- ===================== ROBOT-MAKRO ===================== -->
  <xacro:macro name="mensabot_frame">

    <!-- Roboterbasis -->
    <link name="base_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry><box size="0.5 0.3 0.1"/></geometry> <!-- Beispiel-Chassis -->
        <material name="grey"/>
      </visual>
    </link>
    <joint name="base_joint" type="fixed">
      <parent link="drive_base_link"/>
      <child link="base_link"/>
      <origin xyz="-0.2 0 0.125" rpy="0 0 0"/>  <!-- dies ist der wahre Versatz! -->
    </joint>

    <link name="drive_base_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <sphere radius="0.01"/>
        </geometry>
        <material name="red"/>
      </visual>
    </link>
    

    <!-- Grundstruktur -->
    <xacro:mensabot_rod prefix="mid_front_bottom" parent="base_link" position="0.355 0 0" rotation="0 0 ${pi/2}" length="0.538" color="grey"/>
    <!-- <xacro:mensabot_rod prefix="mid_second" parent="base_link" position="0.070 0 0" rotation="0 0 ${pi/2}" length="0.538" color="grey"/>
    <xacro:mensabot_rod prefix="mid_third" parent="base_link" position="-0.180 0 0" rotation="0 0 ${pi/2}" length="0.538" color="grey"/> -->
    <xacro:mensabot_rod prefix="mid_back_bottom" parent="base_link" position="-0.355 0 0" rotation="0 0 ${pi/2}" length="0.538" color="grey"/>
    <xacro:mensabot_rod prefix="side_left_bottom" parent="base_link" position="0 0.2915 0" rotation="0 0 0" length="0.755" color="grey"/>
    <xacro:mensabot_rod prefix="side_right_bottom" parent="base_link" position="0 -0.2915 0" rotation="0 0 0" length="0.755" color="grey"/>

    <xacro:mensabot_rod prefix="mid_front_top" parent="base_link" position="0.355 0 0.295" rotation="0 0 ${pi/2}" length="0.538" color="grey"/>
    <!-- <xacro:mensabot_rod prefix="mid_second" parent="base_link" position="0.070 0 0" rotation="0 0 ${pi/2}" length="0.538" color="grey"/>
    <xacro:mensabot_rod prefix="mid_third" parent="base_link" position="-0.180 0 0" rotation="0 0 ${pi/2}" length="0.538" color="grey"/> -->
    <xacro:mensabot_rod prefix="mid_back_top" parent="base_link" position="-0.355 0 0.295" rotation="0 0 ${pi/2}" length="0.538" color="grey"/>
    <xacro:mensabot_rod prefix="side_left_top" parent="base_link" position="0 0.2915 0.295" rotation="0 0 0" length="0.755" color="grey"/>
    <xacro:mensabot_rod prefix="side_right_top" parent="base_link" position="0 -0.2915 0.295" rotation="0 0 0" length="0.755" color="grey"/>

    <!-- Senkrecht -->
    <xacro:mensabot_rod prefix="front_right1" parent="base_link" position="0.355 0.2015 0.1475" rotation="0 ${pi/2} 0" length="0.25" color="grey"/>
    <xacro:mensabot_rod prefix="front_left1" parent="base_link" position="0.355 -0.2015 0.1475" rotation="0 ${pi/2} 0" length="0.25" color="grey"/>
    <xacro:mensabot_rod prefix="front_right2" parent="base_link" position="0.265 0.2915 0.1475" rotation="0 ${pi/2} 0" length="0.25" color="grey"/>
    <xacro:mensabot_rod prefix="front_left2" parent="base_link" position="0.265 -0.2915 0.1475" rotation="0 ${pi/2} 0" length="0.25" color="grey"/>
    <xacro:mensabot_rod prefix="back_left1" parent="base_link" position="-0.355 -0.2015 0.1475" rotation="0 ${pi/2} 0" length="0.25" color="grey"/>
    <xacro:mensabot_rod prefix="back_right1" parent="base_link" position="-0.355 0.2015 0.1475" rotation="0 ${pi/2} 0" length="0.25" color="grey"/>
    <xacro:mensabot_rod prefix="back_left2" parent="base_link" position="-0.265 -0.2915 0.1475" rotation="0 ${pi/2} 0" length="0.25" color="grey"/>
    <xacro:mensabot_rod prefix="back_right2" parent="base_link" position="-0.265 0.2915 0.1475" rotation="0 ${pi/2} 0" length="0.25" color="grey"/>
    
    <!-- Box-Komponenten -->
    <xacro:mensabot_box postfix="battery" parent="base_link" position="-0.180 0 0.0625" rotation="0 0 0" length="0.280" width="0.22" height="0.07" weight="17.5" color="red"/>
    
    <!-- Angetriebene RÃ¤der -->
    <xacro:mensabot_wheel prefix="left" parent="base_link" position="0.200 0.20 -0.05" rotation="${pi} 0 0" radius="0.110" width="0.050" weight="2" color="white"/>
    <xacro:mensabot_wheel prefix="right" parent="base_link" position="0.200 -0.20 -0.05" rotation="0 0 0" radius="0.110" width="0.050" weight="2" color="white"/>
    
    <!-- Motoren -->
    <xacro:mensabot_motor prefix="left" parent="base_link" position="0.0275 0.0 0.09" rotation="0 0 0" radius="0.031" width="0.25" weight="5" color="red"/>
    <xacro:mensabot_motor prefix="right" parent="base_link" position="0.1 0.0 0.09" rotation="0 0 0" radius="0.031" width="0.25" weight="5" color="red"/>

    <!-- Castor-Wheels -->
    <xacro:mensabot_castor_wheel prefix="castor_left" parent="base_link" position="-0.250 0.2 -0.085" rotation="0 0 0" radius="0.0625" width="0.040" weight="2" color="black"/>
    <xacro:mensabot_castor_wheel prefix="castor_right" parent="base_link" position="-0.250 -0.2 -0.085" rotation="0 0 0" radius="0.0625" width="0.040" weight="2" color="black"/>

    <!-- Sensoren -->
    <xacro:mensabot_camera prefix="front_camera" parent="base_link" position="0.10 0.00 0.5" rotation="-1.5708 0 -1.5708" color="blue"/>
    <xacro:mensabot_lidar prefix="lidar_front" parent="base_link" position="0.3775 0.314 0.1" rotation="0 0 0" radius="0.06" width="0.05" color="green"/>
    <xacro:mensabot_lidar prefix="lidar_back" parent="base_link" position="-0.3775 -0.314 0.1" rotation="0 0 0" radius="0.06" width="0.05" color="green"/>

  </xacro:macro>

  <!-- ===================== MAKROS ===================== -->

  <!-- Kamera -->
  <xacro:macro name="mensabot_camera" params="prefix parent position rotation color=blue">
    <link name="${prefix}_link">
      <visual>
        <geometry><box size="0.10 0.03 0.02"/></geometry>
        <material name="${color}"/>
      </visual>
      <collision>
        <geometry><box size="0.10 0.03 0.02"/></geometry>
      </collision>
      <inertial>
        <mass value="0.1"/>
        <inertia ixx="1e-4" iyy="1e-4" izz="1e-4" ixy="0" ixz="0" iyz="0"/>
      </inertial>
    </link>
    <joint name="${prefix}_joint" type="fixed">
      <parent link="${parent}"/>
      <child link="${prefix}_link"/>
      <origin xyz="${position}" rpy="${rotation}"/>
    </joint>
  </xacro:macro>

  <!-- Lidar -->
  <xacro:macro name="mensabot_lidar" params="prefix parent position rotation radius width color=green">
    <link name="${prefix}_link">
      <visual>
        <geometry><cylinder radius="${radius}" length="${width}"/></geometry>
        <material name="${color}"/>
      </visual>
      <collision>
        <geometry><cylinder radius="${radius}" length="${width}"/></geometry>
      </collision>
      <inertial>
        <mass value="0.05"/>
        <inertia ixx="1e-5" iyy="1e-5" izz="1e-5" ixy="0" ixz="0" iyz="0"/>
      </inertial>
    </link>
    <joint name="${prefix}_joint" type="fixed">
      <parent link="${parent}"/>
      <child link="${prefix}_link"/>
      <origin xyz="${position}" rpy="${rotation}"/>
    </joint>
  </xacro:macro>

  <!-- Wheel -->
  <xacro:macro name="mensabot_wheel" params="prefix parent position rotation radius width weight color=black">
    <link name="${prefix}_wheel">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry><cylinder radius="${radius}" length="${width}"/></geometry>
        <material name="${color}"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry><cylinder radius="${radius}" length="${width}"/></geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0"/>
        <mass value="${weight}"/>
        <inertia ixx="${weight * radius * radius / 2}" iyy="${weight * (3*radius*radius + width*width)/12}" izz="${weight * (3*radius*radius + width*width)/12}" ixy="0" ixz="0" iyz="0"/>
      </inertial>
    </link>
    <joint name="${prefix}_wheel_joint" type="continuous">
      <axis xyz="0 1 0"/>
      <parent link="${parent}"/>
      <child link="${prefix}_wheel"/>
      <origin xyz="${position}" rpy="${rotation}"/>
    </joint>
  </xacro:macro>

  <!-- Rod -->
  <xacro:macro name="mensabot_rod" params="prefix parent position rotation length color=grey">
    <link name="${prefix}_mensabot_rod">
      <visual>
        <geometry><box size="${length} 0.045 0.045"/></geometry>
        <material name="${color}"/>
      </visual>
      <collision>
        <geometry><box size="${length} 0.045 0.045"/></geometry>
      </collision>
      <inertial>
        <mass value="${rod_weight_per_meter * length}"/>
        <inertia ixx="${rod_weight_per_meter * length * (0.04*0.04 + 0.04*0.04)/12}" 
                 iyy="${rod_weight_per_meter * length * (0.04*0.04 + length*length)/12}" 
                 izz="${rod_weight_per_meter * length * (0.04*0.04 + length*length)/12}" ixy="0" ixz="0" iyz="0"/>
      </inertial>
    </link>
    <joint name="${prefix}_mensabot_rod_joint" type="fixed">
      <parent link="${parent}"/>
      <child link="${prefix}_mensabot_rod"/>
      <origin xyz="${position}" rpy="${rotation}"/>
    </joint>
  </xacro:macro>

  <!-- Box -->
  <xacro:macro name="mensabot_box" params="postfix parent position rotation length width height weight color=grey">
    <link name="mensabot_${postfix}">
      <visual>
        <geometry><box size="${length} ${width} ${height}"/></geometry>
        <material name="${color}"/>
      </visual>
      <collision>
        <geometry><box size="${length} ${width} ${height}"/></geometry>
      </collision>
      <inertial>
        <mass value="${weight}"/>
        <inertia ixx="${weight * (height*height + width*width)/12}" 
                 iyy="${weight * (height*height + length*length)/12}" 
                 izz="${weight * (width*width + length*length)/12}" ixy="0" ixz="0" iyz="0"/>
      </inertial>
    </link>
    <joint name="mensabot_${postfix}_joint" type="fixed">
      <parent link="${parent}"/>
      <child link="mensabot_${postfix}"/>
      <origin xyz="${position}" rpy="${rotation}"/>
    </joint>
  </xacro:macro>

  <!-- Motor -->
  <xacro:macro name="mensabot_motor" params="prefix parent position rotation radius width weight color=black">
    <link name="${prefix}_motor">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry><cylinder radius="${radius}" length="${width}"/></geometry>
        <material name="${color}"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry><cylinder radius="${radius}" length="${width}"/></geometry>
      </collision>
      <inertial>
        <mass value="${weight}"/>
        <inertia ixx="${weight * radius * radius / 2}" iyy="${weight * (3*radius*radius + width*width)/12}" izz="${weight * (3*radius*radius + width*width)/12}" ixy="0" ixz="0" iyz="0"/>
      </inertial>
    </link>
    <joint name="${prefix}_motor_joint" type="fixed">
      <parent link="${parent}"/>
      <child link="${prefix}_motor"/>
      <origin xyz="${position}" rpy="${rotation}"/>
    </joint>
  </xacro:macro>

    <!-- Castor wheel (fixed version for RViz simulation) -->
  <xacro:macro name="mensabot_castor_wheel" params="prefix parent position rotation radius width weight color=black">
    <link name="${prefix}_castor_wheel">
      <visual>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${radius}" length="${width}"/>
        </geometry>
        <material name="${color}"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${radius}" length="${width}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0"/>
        <mass value="${weight}"/>
        <inertia
          ixx="${weight * radius * radius / 2}"
          iyy="${weight * (3*radius*radius + width*width)/12}"
          izz="${weight * (3*radius*radius + width*width)/12}"
          ixy="0" ixz="0" iyz="0"/>
      </inertial>
    </link>

    <!-- FIXED joint instead of rotating one -->
    <joint name="${prefix}_castor_wheel_joint" type="fixed">
      <parent link="${parent}"/>
      <child link="${prefix}_castor_wheel"/>
      <origin xyz="${position}" rpy="${rotation}"/>
    </joint>
  </xacro:macro>


</robot>

